# Generated by Django 3.1.6 on 2021-02-03 15:12

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20210203_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
